/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import domainModel.NhanVien;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import service.ServiceNhanVien;
import service.impl.ServiceNhanVienImpl;


/**
 *
 * @author dongl
 */
public class viewQLNhanVien extends javax.swing.JPanel {

    /**
     * Creates new form viewQLNhanVien
     */
    private DefaultTableModel dtm = new DefaultTableModel();
    private ServiceNhanVien ss = new ServiceNhanVienImpl();
    private List<NhanVien> _list = ss.getList();

    public viewQLNhanVien() {
        initComponents();
        this.loadTable(ss.getList());
    }

    private void loadTable(List<NhanVien> list) {
        dtm = (DefaultTableModel) tblNhanVien.getModel();
        dtm.setRowCount(0);
        int stt = 1;
        for (NhanVien x : list) {
            dtm.addRow(new Object[]{
                stt, x.getMa(), x.getHoTen(), x.getTenDangNhap(), x.getMatKhau(), x.getSdt(), x.getDiaChi(), x.getEmail(),
                x.getGioiTinh() == 1 ? "Nam" : "Nữ", x.getChucVu() == 1 ? "Nhân viên" : "Quản lý", x.getTrangThaiLamViec()==1?"Đi làm":"Nghỉ việc"
            });
            stt++;
        }
//        ss.getList().forEach(x -> dtm.addRow(new Object[]{
//            stt, x.getMa(), x.getHoTen(), x.getTenDangNhap(), x.getMatKhau(), x.getSdt(), x.getDiaChi(), x.getEmail(),
//            x.getGioiTinh() == 1 ? "Nam" : "Nữ", x.getChucVu() == 1 ? "Nhân viên" : "Quản lý"
//        }));
    }

    private NhanVien getDataForm() {
        if (txtMaNV.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Mã nhân viên không được để trống");
            txtMaNV.requestFocus();
            return null;
        }
        if (txtTenDN.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Tên đăng nhập không được để trống");
            txtTenDN.requestFocus();
            return null;
        }
        if (txtHoTen.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Họ tên không được để trống");
            txtHoTen.requestFocus();
            return null;
        }
        if (txtSDT.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Số điện thoại không được để trống");
            txtSDT.requestFocus();
            return null;
        }
        if (txtDiaChi.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Địa chỉ không được để trống");
            txtDiaChi.requestFocus();
            return null;
        }
        if (txtEmail.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Email không được để trống");
            txtEmail.requestFocus();
            return null;
        }
        if (txtMatKhau.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Mật khẩu không được để trống");
            txtMatKhau.requestFocus();
            return null;
        }
        Integer trangThai = 1;
        String tt = this.cboTrangThai.getSelectedItem().toString();
        if (tt.equals("Nghỉ việc")) {
            trangThai = 2;
        }
        return new NhanVien(null, txtMaNV.getText().trim(), txtTenDN.getText().trim(),
                txtHoTen.getText().trim(), rdoNam.isSelected() ? 1 : 2, txtSDT.getText().trim(),
                txtDiaChi.getText().trim(), txtEmail.getText().trim(), txtMatKhau.getText().trim(),
                trangThai, rdoNhanVien.isSelected() ? 1 : 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        btnSua = new swing.ButtonCustom();
        btnThem = new swing.ButtonCustom();
        btnClearForm = new swing.ButtonCustom();
        btnXuatDS = new swing.ButtonCustom();
        jPanel4 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        btnTimKiem = new swing.ButtonCustom();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        cboNhanVien = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        rdoQuanLy = new javax.swing.JRadioButton();
        rdoNhanVien = new javax.swing.JRadioButton();
        txtTenDN = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        cboTrangThai = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        btnSua.setBackground(new java.awt.Color(255, 0, 0));
        btnSua.setForeground(new java.awt.Color(255, 255, 255));
        btnSua.setText("Sửa");
        btnSua.setFont(new java.awt.Font("Consolas", 1, 17)); // NOI18N
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(255, 0, 0));
        btnThem.setForeground(new java.awt.Color(255, 255, 255));
        btnThem.setText("Thêm");
        btnThem.setFont(new java.awt.Font("Consolas", 1, 17)); // NOI18N
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnClearForm.setBackground(new java.awt.Color(0, 153, 102));
        btnClearForm.setForeground(new java.awt.Color(255, 255, 255));
        btnClearForm.setText("Clear Form");
        btnClearForm.setFont(new java.awt.Font("Consolas", 1, 17)); // NOI18N
        btnClearForm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearFormActionPerformed(evt);
            }
        });

        btnXuatDS.setBackground(new java.awt.Color(0, 153, 102));
        btnXuatDS.setForeground(new java.awt.Color(255, 255, 255));
        btnXuatDS.setText("Xuất DS");
        btnXuatDS.setFont(new java.awt.Font("Consolas", 1, 17)); // NOI18N
        btnXuatDS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatDSActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Tìm kiếm"));

        txtTimKiem.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTimKiemCaretUpdate(evt);
            }
        });

        btnTimKiem.setBackground(new java.awt.Color(0, 204, 204));
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Tìm kiếm");
        btnTimKiem.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnClearForm, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXuatDS, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnClearForm, btnSua, btnThem, btnXuatDS});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClearForm, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXuatDS, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 0, -1, -1));

        tblNhanVien.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tblNhanVien.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã NV", "Họ tên", "Tên đăng nhập", "Mật khẩu", "SĐT", "Địa chỉ", "Email", "Giới tính", "Chức vụ", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhanVien.setRowHeight(40);
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 511, 1115, 270));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("DANH SÁCH NHÂN VIÊN");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 459, -1, -1));

        cboNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất cả nhân viên", "Đang đi làm", "Đã nghỉ" }));
        cboNhanVien.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboNhanVienItemStateChanged(evt);
            }
        });
        add(cboNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 460, 213, 38));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel12.setText("Mã nhân viên");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 39, -1, 26));
        jPanel3.add(txtMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 37, 190, 34));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel13.setText("Họ và tên");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, -1, 26));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel14.setText("Tên đăng nhập");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, -1, 26));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel16.setText("Mật khẩu");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, -1, 26));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel18.setText("Số điện thoại");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, 26));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel19.setText("Email");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, -1, 26));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel21.setText("Giới tính");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, 26));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel22.setText("Chức vụ");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 350, -1, 26));

        buttonGroup1.add(rdoNam);
        rdoNam.setSelected(true);
        rdoNam.setText("Nam");
        jPanel3.add(rdoNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 350, -1, -1));

        buttonGroup1.add(rdoNu);
        rdoNu.setText("Nữ");
        jPanel3.add(rdoNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        buttonGroup2.add(rdoQuanLy);
        rdoQuanLy.setText("Quản lý");
        jPanel3.add(rdoQuanLy, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, -1, -1));

        buttonGroup2.add(rdoNhanVien);
        rdoNhanVien.setSelected(true);
        rdoNhanVien.setText("Nhân viên");
        jPanel3.add(rdoNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 350, -1, -1));
        jPanel3.add(txtTenDN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 190, 34));
        jPanel3.add(txtSDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 190, 34));
        jPanel3.add(txtHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 190, 34));
        jPanel3.add(txtMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 190, 34));
        jPanel3.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, 190, 34));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel20.setText("Địa chỉ");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 26));
        jPanel3.add(txtDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 190, 34));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel23.setText("Trạng thái");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, -1, 26));

        cboTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đi làm", "Nghỉ việc" }));
        jPanel3.add(cboTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 270, 190, 34));

        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 633, 453));
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearFormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearFormActionPerformed
        // TODO add your handling code here:
        this.txtMaNV.setText("");
        this.txtHoTen.setText("");
        this.txtTenDN.setText("");
        this.txtMatKhau.setText("");
        this.txtSDT.setText("");
        this.txtEmail.setText("");
        this.txtDiaChi.setText("");
        rdoNam.setSelected(true);
        rdoNhanVien.setSelected(true);
        this.cboTrangThai.setSelectedIndex(0);

    }//GEN-LAST:event_btnClearFormActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        String text = this.txtTimKiem.getText().trim();
        if(text.trim().length()==0){
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập nội dung tìm kiếm!!!");
            return;
        }
        List<NhanVien> list = ss.getListByTen(text);
        this.loadTable(list);
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        // TODO add your handling code here:
        int row = this.tblNhanVien.getSelectedRow();
        if (row == -1) {
            return;
        }

        String maNV = this.tblNhanVien.getValueAt(row, 1).toString();
        NhanVien nv = ss.getNhanVienByMa(maNV);
        String hoTen = this.tblNhanVien.getValueAt(row, 2).toString();
        String tenDN = this.tblNhanVien.getValueAt(row, 3).toString();
        String matKhau = this.tblNhanVien.getValueAt(row, 4).toString();
        String sdt = this.tblNhanVien.getValueAt(row, 5).toString();
        String diaChi = this.tblNhanVien.getValueAt(row, 6).toString();
        String email = this.tblNhanVien.getValueAt(row, 7).toString();
        String gioiTinh = this.tblNhanVien.getValueAt(row, 8).toString();
        String chucVu = this.tblNhanVien.getValueAt(row, 9).toString();

        this.txtMaNV.setText(maNV);
        this.txtHoTen.setText(hoTen);
        this.txtTenDN.setText(tenDN);
        this.txtMatKhau.setText(matKhau);
        this.txtSDT.setText(sdt);
        this.txtEmail.setText(email);
        this.txtDiaChi.setText(diaChi);
        if (gioiTinh.equals("Nam")) {
            rdoNam.setSelected(true);
        } else {
            rdoNu.setSelected(true);
        }
        if (chucVu.equals("Nhân viên")) {
            rdoNhanVien.setSelected(true);
        } else {
            rdoQuanLy.setSelected(true);
        }
        if (nv.getTrangThaiLamViec() == 1) {
            this.cboTrangThai.setSelectedIndex(0);
        } else {
            this.cboTrangThai.setSelectedIndex(1);
        }
    }//GEN-LAST:event_tblNhanVienMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        NhanVien nv = this.getDataForm();
        if (nv == null) {
            return;
        }
        if (ss.insert(nv)) {
            JOptionPane.showMessageDialog(this, "Thêm thành công");
            this.loadTable(ss.getList());
            btnClearFormActionPerformed(evt);
            return;
        }
        JOptionPane.showMessageDialog(this, "Đã có mã nhân viên này");
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        NhanVien nv = this.getDataForm();
        if (nv == null) {
            return;
        }
        Boolean check = ss.update(nv, txtMaNV.getText().trim());
        if (check) {
            JOptionPane.showMessageDialog(this, "Sửa thành công");
            this.loadTable(ss.getList());
            btnClearFormActionPerformed(evt);
        } else {
            JOptionPane.showMessageDialog(this, "Đã có mã nhân viên này");

        }
        //JOptionPane.showMessageDialog(this, "Sửa thất bại");
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXuatDSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatDSActionPerformed
        // TODO add your handling code here:
        FileOutputStream excelFOU = null;
        BufferedOutputStream excelBOU = null;
        XSSFWorkbook excelJTableExporter = null;

        //Choose Location For Saving Excel File
        JFileChooser excelFileChooser = new JFileChooser("C:\\Users\\dongl\\OneDrive\\Máy tính");
        //        Change Dilog Box Title
        excelFileChooser.setDialogTitle("Save As");
        //        Onliny filter files with these extensions "xls", "xlsx", "xlsm"
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("EXCEL FILES", "xls", "xlsx", "xlsm");
        excelFileChooser.setFileFilter(fnef);
        int excelChooser = excelFileChooser.showSaveDialog(null);

        //        Check if save button is clicked
        if (excelChooser == JFileChooser.APPROVE_OPTION) {

            try {
                //Import excel poi libraries to netbeans
                int index = 0;
                int stt = 1;
                excelJTableExporter = new XSSFWorkbook();

                XSSFSheet excelSheet = excelJTableExporter.createSheet("JTable Sheet");
                Row firstRow = excelSheet.createRow(index++);

                Cell soTT = firstRow.createCell(0);
                soTT.setCellValue("STT");

                Cell maNhanVien = firstRow.createCell(1);
                maNhanVien.setCellValue("Mã nhân viên");
                
                Cell hoTen = firstRow.createCell(2);
                hoTen.setCellValue("Họ tên");
                
                Cell tenDangNhap = firstRow.createCell(3);
                tenDangNhap.setCellValue("Tên đăng nhập");
                
                Cell matKhau = firstRow.createCell(4);
                matKhau.setCellValue("Mật khẩu");
                
                Cell sdt = firstRow.createCell(5);
                sdt.setCellValue("SĐT");
                
                Cell dc = firstRow.createCell(6);
                dc.setCellValue("Địa chỉ");
                
                Cell email = firstRow.createCell(7);
                email.setCellValue("Email");
                
                Cell gt = firstRow.createCell(8);
                gt.setCellValue("Giới tính");
                
                Cell cv = firstRow.createCell(9);
                cv.setCellValue("Chức vụ");
                
                Cell tt = firstRow.createCell(10);
                tt.setCellValue("Trạng thái");
                
                for (NhanVien x : _list) {
                Row row = excelSheet.createRow(index++);

                Cell cell0 = row.createCell(0);
                cell0.setCellValue(stt++);

                Cell cell1 = row.createCell(1);
                cell1.setCellValue(x.getMa());

                Cell cell2 = row.createCell(2);
                cell2.setCellValue(x.getHoTen());

                Cell cell3 = row.createCell(3);
                cell3.setCellValue(x.getTenDangNhap());

                Cell cell4 = row.createCell(4);
                cell4.setCellValue(x.getMatKhau());

                Cell cell5 = row.createCell(5);
                cell5.setCellValue(x.getSdt());

                Cell cell6 = row.createCell(6);
                cell6.setCellValue(x.getDiaChi());

                Cell cell7 = row.createCell(7);
                cell7.setCellValue(x.getEmail());

                Cell cell8 = row.createCell(8);
                cell8.setCellValue(x.getGioiTinh()==1?"Nam":"Nữ");

                Cell cell9 = row.createCell(9);
                cell9.setCellValue(x.getChucVu()== 2 ? "Quản lý" : "Nhân viên");
                
                Cell cell10 = row.createCell(10);
                cell10.setCellValue(x.getTrangThaiLamViec()==1?"Đi làm":"Nghỉ việc");
            }
                excelFOU = new FileOutputStream(excelFileChooser.getSelectedFile() + ".xlsx");
                excelBOU = new BufferedOutputStream(excelFOU);
                excelJTableExporter.write(excelBOU);
                JOptionPane.showMessageDialog(null, "Xuất danh sách thành công");
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            } catch (IOException ex) {
                ex.printStackTrace();
            } finally {
                try {
                    if (excelBOU != null) {
                        excelBOU.close();
                    }
                    if (excelFOU != null) {
                        excelFOU.close();
                    }
                    if (excelJTableExporter != null) {
                        //excelJTableExporter.close();
                    }
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_btnXuatDSActionPerformed

    private void cboNhanVienItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboNhanVienItemStateChanged
        // TODO add your handling code here:
        String item = this.cboNhanVien.getSelectedItem().toString();
        _list = ss.getListByTT(item.equals("Đang đi làm")?1:item.equals("Đã nghỉ")?2:-1);
        this.loadTable(_list);
        if(item.equals("Tất cả nhân viên")){
            _list = ss.getList();
            this.loadTable(_list);
        }
    }//GEN-LAST:event_cboNhanVienItemStateChanged

    private void txtTimKiemCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTimKiemCaretUpdate
        // TODO add your handling code here:
        if(txtTimKiem.getText().trim().length() ==0){
            this.loadTable(ss.getList());
            this.cboNhanVien.setSelectedIndex(0);
        }
    }//GEN-LAST:event_txtTimKiemCaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ButtonCustom btnClearForm;
    private swing.ButtonCustom btnSua;
    private swing.ButtonCustom btnThem;
    private swing.ButtonCustom btnTimKiem;
    private swing.ButtonCustom btnXuatDS;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cboNhanVien;
    private javax.swing.JComboBox<String> cboTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNhanVien;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JRadioButton rdoQuanLy;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTenDN;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
