/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import chart.Chart;
import chart.ModelChart;
import com.toedter.calendar.JMonthChooser;
import domainModel.HoaDon;
import domainModel.HoaDonChiTiet;
import java.awt.Color;
import java.math.BigDecimal;
import java.math.MathContext;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import service.ServiceHoaDon;
import service.ServiceHoaDonChiTiet;
import service.impl.ServiceHoaDonChiTietImpl;
import service.impl.ServiceHoaDonImpl;

/**
 *
 * @author dongl
 */
public class viewThongKe extends javax.swing.JPanel {

    /**
     * Creates new form viewThongKe
     */
    private ServiceHoaDon ssHoaDon = new ServiceHoaDonImpl();
    private ServiceHoaDonChiTiet ssHDCT = new ServiceHoaDonChiTietImpl();
    private Chart chart = new Chart();
    BigDecimal doanhThu = new BigDecimal(0);
    Integer soHD = 0;
    Integer soThungBia = 0;
    Integer soLonBia = 0;
    Integer soKhachHang = 0;

    public viewThongKe() {
        initComponents();
        chart1.addData(new ModelChart("February", new double[]{600, 750, 90, 150}));
        chart1.addData(new ModelChart("March", new double[]{200, 350, 460, 900}));
        chart1.addData(new ModelChart("April", new double[]{480, 150, 750, 700}));
        chart1.addData(new ModelChart("May", new double[]{350, 540, 300, 150}));
        chart1.addData(new ModelChart("June", new double[]{190, 280, 81, 200}));
        chart1.addData(new ModelChart("July", new double[]{190, 280, 81, 440}));
        chart1.addData(new ModelChart("August", new double[]{190, 280, 81, 20}));
        chart1.addData(new ModelChart("September", new double[]{90, 220, 81, 400}));
        chart1.addData(new ModelChart("October", new double[]{110, 111, 55, 110}));
        chart1.addData(new ModelChart("November", new double[]{40, 180, 81, 250}));
        chart1.addData(new ModelChart("December", new double[]{97, 380, 81, 100}));

    }

    private void resetData() {
        doanhThu = new BigDecimal(0);
        soHD = 0;
        soThungBia = 0;
        soLonBia = 0;
        soKhachHang = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMonth = new com.toedter.calendar.JMonthChooser();
        txtYear = new com.toedter.calendar.JYearChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtDoanhThu = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtSoHoaDon = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtSoThungBia = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        txtSoLonBia = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnTimKiem = new swing.ButtonCustom();
        jPanel7 = new javax.swing.JPanel();
        txtSoKhachHang = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cboLoai = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        pnlLoai = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnTimKiem1 = new swing.ButtonCustom();
        jLabel16 = new javax.swing.JLabel();
        txtFrom = new com.toedter.calendar.JDateChooser();
        txtTo = new com.toedter.calendar.JDateChooser();
        jLabel17 = new javax.swing.JLabel();
        chart1 = new chart.Chart();
        lblTieuDe = new javax.swing.JLabel();

        txtYear.setMinimumSize(new java.awt.Dimension(107, 38));
        txtYear.setPreferredSize(new java.awt.Dimension(107, 24));

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1140, 821));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(140, 140));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Nunito Light", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Doanh thu");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 13, 130, 32));

        txtDoanhThu.setFont(new java.awt.Font("Nunito Light", 1, 14)); // NOI18N
        txtDoanhThu.setForeground(new java.awt.Color(255, 255, 255));
        txtDoanhThu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtDoanhThu.setText("...");
        jPanel2.add(txtDoanhThu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 63, 130, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 119, 130, 110));

        jPanel4.setBackground(new java.awt.Color(255, 51, 51));
        jPanel4.setPreferredSize(new java.awt.Dimension(140, 140));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSoHoaDon.setFont(new java.awt.Font("Nunito Light", 1, 14)); // NOI18N
        txtSoHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        txtSoHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSoHoaDon.setText("...");
        jPanel4.add(txtSoHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 60, 130, 31));

        jLabel3.setFont(new java.awt.Font("Nunito Light", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Số hóa đơn");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 32));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 130, 110));

        jPanel5.setBackground(new java.awt.Color(255, 51, 51));
        jPanel5.setPreferredSize(new java.awt.Dimension(140, 140));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSoThungBia.setFont(new java.awt.Font("Nunito Light", 1, 14)); // NOI18N
        txtSoThungBia.setForeground(new java.awt.Color(255, 255, 255));
        txtSoThungBia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSoThungBia.setText("...");
        jPanel5.add(txtSoThungBia, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 60, 130, 31));

        jLabel4.setFont(new java.awt.Font("Nunito Light", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Số thùng bia");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 32));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 130, 110));

        jPanel6.setBackground(new java.awt.Color(255, 51, 51));
        jPanel6.setPreferredSize(new java.awt.Dimension(140, 140));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSoLonBia.setFont(new java.awt.Font("Nunito Light", 1, 14)); // NOI18N
        txtSoLonBia.setForeground(new java.awt.Color(255, 255, 255));
        txtSoLonBia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSoLonBia.setText("...");
        jPanel6.add(txtSoLonBia, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 60, 130, 31));

        jLabel5.setFont(new java.awt.Font("Nunito Light", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Số lon bia");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 32));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 130, 110));

        btnTimKiem.setBackground(new java.awt.Color(0, 204, 204));
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem.setText("Kiểm tra");
        btnTimKiem.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        jPanel1.add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 30, 120, 60));

        jPanel7.setBackground(new java.awt.Color(255, 51, 51));
        jPanel7.setPreferredSize(new java.awt.Dimension(140, 140));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtSoKhachHang.setFont(new java.awt.Font("Nunito Light", 1, 14)); // NOI18N
        txtSoKhachHang.setForeground(new java.awt.Color(255, 255, 255));
        txtSoKhachHang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtSoKhachHang.setText("...");
        jPanel7.add(txtSoKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 60, 130, 31));

        jLabel6.setFont(new java.awt.Font("Nunito Light", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Số khách hàng");
        jPanel7.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 32));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 130, 110));

        cboLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theo ngày", "Theo tháng", "Theo năm" }));
        cboLoai.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboLoaiItemStateChanged(evt);
            }
        });
        jPanel1.add(cboLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 120, 30));

        jLabel2.setText("Loại");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 46, -1, -1));

        pnlLoai.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlLoaiLayout = new javax.swing.GroupLayout(pnlLoai);
        pnlLoai.setLayout(pnlLoaiLayout);
        pnlLoaiLayout.setHorizontalGroup(
            pnlLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnlLoaiLayout.setVerticalGroup(
            pnlLoaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLoaiLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel1.add(pnlLoai, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, 220, 80));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Thống kê theo khoảng thời gian", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Nunito Light", 1, 14))); // NOI18N

        btnTimKiem1.setBackground(new java.awt.Color(0, 204, 204));
        btnTimKiem1.setForeground(new java.awt.Color(255, 255, 255));
        btnTimKiem1.setText("Kiểm tra");
        btnTimKiem1.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        btnTimKiem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiem1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel16.setText("Đến ngày");

        txtFrom.setDateFormatString("dd-MM-yyyy");

        txtTo.setDateFormatString("dd-MM-yyyy");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 17)); // NOI18N
        jLabel17.setText("Từ ngày");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTimKiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chart1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnTimKiem1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(8, 8, 8)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtTo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chart1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
        );

        lblTieuDe.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTieuDe.setText("Thống kê doanh thu theo ngày");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTieuDe)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1128, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(lblTieuDe)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        // TODO add your handling code here:
        Integer date = Integer.parseInt(txtTimKiem.getText().trim());
        String text = this.cboLoai.getSelectedItem().toString();
        List<HoaDon> list = new ArrayList<>();
        DecimalFormat df = new DecimalFormat("#,###");
        if (text.equals("Theo ngày")) {
            if (date > 31) {
                JOptionPane.showMessageDialog(this, "Bạn nhập ngày quá lớn");
                return;
            }
            list = ssHoaDon.getListByNgay(date);
            soHD = list.size();
            for (HoaDon hoaDon : list) {
//                String maHD = hoaDon.getMa();
//                HoaDonChiTiet lst = ssHDCT.getHoaDonCTByMaHD(maHD);
                doanhThu = doanhThu.add(hoaDon.getTongTien());
                soKhachHang++;
                //soLonBia += lst.getSoLuong();
            }
        } else if (text.equals("Theo tháng")) {
            if (date > 12) {
                JOptionPane.showMessageDialog(this, "Bạn nhập tháng quá lớn");
                return;
            }
            list = ssHoaDon.getListByThang(date);
            soHD = list.size();
            for (HoaDon hoaDon : list) {
//                String maHD = hoaDon.getMa();
//                HoaDonChiTiet lst = ssHDCT.getHoaDonCTByMaHD(maHD);
                doanhThu = doanhThu.add(hoaDon.getTongTien());
                soKhachHang++;
                //soLonBia += lst.getSoLuong();
            }
        } else {
            if (date > 2023) {
                JOptionPane.showMessageDialog(this, "Bạn nhập năm quá lớn");
                return;
            }
            list = ssHoaDon.getListByNam(date);
            soHD = list.size();
            for (HoaDon hoaDon : list) {
//                String maHD = hoaDon.getMa();
//                HoaDonChiTiet lst = ssHDCT.getHoaDonCTByMaHD(maHD);
                doanhThu = doanhThu.add(hoaDon.getTongTien());
                soKhachHang++;
                //soLonBia += lst.getSoLuong();
            }
        }
        txtDoanhThu.setText(df.format(doanhThu) + "VNĐ");
        txtSoHoaDon.setText(soHD + "");
        txtSoKhachHang.setText(soKhachHang + "");
        resetData();
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnTimKiem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiem1ActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        DecimalFormat df = new DecimalFormat("#,###");
        Date to = this.txtTo.getDate();
        Date from = this.txtFrom.getDate();
        int index = 1;
        if (to.getTime() > from.getTime()) {
            JOptionPane.showMessageDialog(this, "Ngày bắt đầu lớn hơn ngày kết thúc");
            return;
        }
        List<HoaDon> list = new ArrayList<>();
        list = ssHoaDon.getListByTime(to, from);
        chart1.addLegend("Doanh Thu", new Color(245, 189, 135));
        chart1.addLegend("Hóa Đơn", new Color(135, 189, 245));
        chart1.addLegend("Thùng Bia", new Color(189, 135, 245));
        chart1.addLegend("Lon Bia", new Color(139, 229, 222));
        soHD = list.size();
        for (HoaDon hoaDon : list) {
            doanhThu = doanhThu.add(hoaDon.getTongTien());
            //chart1.addData(new ModelChart("Tháng "+(hoaDon.getNgayThanhToan().getMonth()+1), new double[]{Double.valueOf(doanhThu.toString()), soHD, 11, 11}));
            index++;
        }
//        for (int i = 1; i < index; i++) {
        //chart1.addData(new ModelChart("Doanh Thu :" + df.format(doanhThu), new double[]{Double.valueOf(doanhThu.toString()), soHD, 0, 0}));
        //}

        chart1.addData(new ModelChart("Demo", new double[]{100, 4000, 1000, 1603}));
        chart1.addData(new ModelChart("February", new double[]{600, 750, 90, 150}));
        chart1.addData(new ModelChart("March", new double[]{200, 350, 460, 900}));
        chart1.addData(new ModelChart("April", new double[]{480, 150, 750, 700}));
        chart1.addData(new ModelChart("May", new double[]{350, 540, 300, 150}));
        chart1.addData(new ModelChart("June", new double[]{190, 280, 81, 200}));
        chart1.addData(new ModelChart("July", new double[]{190, 280, 81, 440}));
        chart1.addData(new ModelChart("August", new double[]{190, 280, 81, 20}));
        chart1.addData(new ModelChart("September", new double[]{90, 220, 81, 400}));
        chart1.addData(new ModelChart("October", new double[]{110, 111, 55, 110}));
        chart1.addData(new ModelChart("November", new double[]{40, 180, 81, 250}));
        chart1.addData(new ModelChart("December", new double[]{97, 380, 81, 100}));
    }//GEN-LAST:event_btnTimKiem1ActionPerformed

    private void cboLoaiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboLoaiItemStateChanged
        // TODO add your handling code here:
        String text = this.cboLoai.getSelectedItem().toString();
        lblTieuDe.setText("Thống kê doanh thu " + text.toLowerCase());
    }//GEN-LAST:event_cboLoaiItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ButtonCustom btnTimKiem;
    private swing.ButtonCustom btnTimKiem1;
    private javax.swing.JComboBox<String> cboLoai;
    private chart.Chart chart1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel lblTieuDe;
    private javax.swing.JPanel pnlLoai;
    private javax.swing.JLabel txtDoanhThu;
    private com.toedter.calendar.JDateChooser txtFrom;
    private com.toedter.calendar.JMonthChooser txtMonth;
    private javax.swing.JLabel txtSoHoaDon;
    private javax.swing.JLabel txtSoKhachHang;
    private javax.swing.JLabel txtSoLonBia;
    private javax.swing.JLabel txtSoThungBia;
    private javax.swing.JTextField txtTimKiem;
    private com.toedter.calendar.JDateChooser txtTo;
    private com.toedter.calendar.JYearChooser txtYear;
    // End of variables declaration//GEN-END:variables
}
