/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import domainModel.NhanVien;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Frame;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;
import swing.ThongBao;
import view.QuanLyKhachHang;
import view.ViewQLKH;
import view.viewBanHang;
import view.viewQLKhachHang;
import view.viewQLKhuyenMai;
import view.viewQLNhanVien;
import view.viewQLSanPham;
import view.viewThongKe;

/**
 *
 * @author proxc
 */
public class TrangChu extends javax.swing.JFrame {

    private CardLayout cardLayout;

    public static NhanVien nhanVien = new NhanVien();

    public TrangChu(NhanVien nv) {
        initComponents();
        this.setLocationRelativeTo(null);
//        ThongBao tb = new ThongBao(this, ThongBao.Type.SUCCESS, ThongBao.Location.TOP_CENTER, "Đăng nhập thành công");
//        tb.showNotification();
        TrangChu.this.getRootPane().setBorder(new LineBorder(Color.BLACK));
        this.getContentPane().setBackground(Color.WHITE);
        lblTitle.setText("Phần mềm bán bia đóng sẵn");
        cardLayout = (CardLayout) pnlRight.getLayout();
        String hoTen = viewLogin.nv.getHoTen();
        this.lblTenNhanVien.setText("Xin chào : "+hoTen.substring(hoTen.lastIndexOf(" ")));
        nhanVien = nv;
        //btnBanHangMousePressed(evt);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTop = new javax.swing.JPanel();
        pnlActions = new javax.swing.JPanel();
        lblMinimize = new javax.swing.JLabel();
        lblMaximize = new javax.swing.JLabel();
        lblClose = new javax.swing.JLabel();
        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlParent = new javax.swing.JPanel();
        sidepane = new javax.swing.JPanel();
        btnQLSP = new javax.swing.JPanel();
        ind_typo = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnQLNV = new javax.swing.JPanel();
        ind_fonts = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnQLKH = new javax.swing.JPanel();
        ind_icons = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnQLDKM = new javax.swing.JPanel();
        ind_data = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnThongKe = new javax.swing.JPanel();
        ind_data1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnBanHang = new javax.swing.JPanel();
        ind_typo1 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        lblTenNhanVien = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        pnlRight = new javax.swing.JPanel();
        pnlQLSP = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnlQLNV = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnlQLKH = new javax.swing.JPanel();
        pnlQLVC = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        pnlQLDKM = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        pnlTop.setBackground(new java.awt.Color(0, 0, 0));
        pnlTop.setPreferredSize(new java.awt.Dimension(1024, 30));
        pnlTop.setLayout(new java.awt.BorderLayout());

        pnlActions.setBackground(new java.awt.Color(0, 0, 0));
        pnlActions.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));

        lblMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/thunho.png"))); // NOI18N
        lblMinimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMinimizeMousePressed(evt);
            }
        });
        pnlActions.add(lblMinimize);

        lblMaximize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/phongto.png"))); // NOI18N
        lblMaximize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblMaximizeMousePressed(evt);
            }
        });
        pnlActions.add(lblMaximize);

        lblClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/exitt.png"))); // NOI18N
        lblClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCloseMousePressed(evt);
            }
        });
        pnlActions.add(lblClose);

        pnlTop.add(pnlActions, java.awt.BorderLayout.LINE_END);

        pnlTitle.setBackground(new java.awt.Color(0, 0, 0));
        pnlTitle.setPreferredSize(new java.awt.Dimension(200, 30));
        pnlTitle.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 8));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(204, 204, 204));
        lblTitle.setText("Phần mềm bán bia đóng sẵn");
        pnlTitle.add(lblTitle);

        pnlTop.add(pnlTitle, java.awt.BorderLayout.LINE_START);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Phần mềm bán bia đóng sẵn");
        setLocationByPlatform(true);

        pnlParent.setLayout(new java.awt.BorderLayout());

        sidepane.setBackground(new java.awt.Color(0, 0, 0));
        sidepane.setForeground(new java.awt.Color(51, 51, 51));
        sidepane.setPreferredSize(new java.awt.Dimension(250, 200));
        sidepane.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                sidepaneMouseDragged(evt);
            }
        });
        sidepane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sidepaneMousePressed(evt);
            }
        });

        btnQLSP.setBackground(new java.awt.Color(0, 0, 0));
        btnQLSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnQLSPMousePressed(evt);
            }
        });
        btnQLSP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_typo.setOpaque(false);
        ind_typo.setPreferredSize(new java.awt.Dimension(4, 40));

        javax.swing.GroupLayout ind_typoLayout = new javax.swing.GroupLayout(ind_typo);
        ind_typo.setLayout(ind_typoLayout);
        ind_typoLayout.setHorizontalGroup(
            ind_typoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_typoLayout.setVerticalGroup(
            ind_typoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btnQLSP.add(ind_typo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel12.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Sản phẩm");
        btnQLSP.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/icon_bia.png"))); // NOI18N

        btnQLNV.setBackground(new java.awt.Color(0, 0, 0));
        btnQLNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnQLNVMousePressed(evt);
            }
        });
        btnQLNV.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_fonts.setOpaque(false);
        ind_fonts.setPreferredSize(new java.awt.Dimension(4, 40));

        javax.swing.GroupLayout ind_fontsLayout = new javax.swing.GroupLayout(ind_fonts);
        ind_fonts.setLayout(ind_fontsLayout);
        ind_fontsLayout.setHorizontalGroup(
            ind_fontsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_fontsLayout.setVerticalGroup(
            ind_fontsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btnQLNV.add(ind_fonts, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel5.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Nhân viên");
        btnQLNV.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        btnQLKH.setBackground(new java.awt.Color(0, 0, 0));
        btnQLKH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnQLKHMousePressed(evt);
            }
        });
        btnQLKH.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_icons.setOpaque(false);
        ind_icons.setPreferredSize(new java.awt.Dimension(4, 40));

        javax.swing.GroupLayout ind_iconsLayout = new javax.swing.GroupLayout(ind_icons);
        ind_icons.setLayout(ind_iconsLayout);
        ind_iconsLayout.setHorizontalGroup(
            ind_iconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_iconsLayout.setVerticalGroup(
            ind_iconsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btnQLKH.add(ind_icons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel6.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Khách hàng");
        btnQLKH.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 20));

        btnQLDKM.setBackground(new java.awt.Color(0, 0, 0));
        btnQLDKM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnQLDKMMousePressed(evt);
            }
        });
        btnQLDKM.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_data.setOpaque(false);
        ind_data.setPreferredSize(new java.awt.Dimension(4, 40));

        javax.swing.GroupLayout ind_dataLayout = new javax.swing.GroupLayout(ind_data);
        ind_data.setLayout(ind_dataLayout);
        ind_dataLayout.setHorizontalGroup(
            ind_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_dataLayout.setVerticalGroup(
            ind_dataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btnQLDKM.add(ind_data, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel10.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Đợt khuyến mại");
        btnQLDKM.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 30));

        btnThongKe.setBackground(new java.awt.Color(0, 0, 0));
        btnThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnThongKeMousePressed(evt);
            }
        });
        btnThongKe.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_data1.setOpaque(false);
        ind_data1.setPreferredSize(new java.awt.Dimension(4, 40));

        javax.swing.GroupLayout ind_data1Layout = new javax.swing.GroupLayout(ind_data1);
        ind_data1.setLayout(ind_data1Layout);
        ind_data1Layout.setHorizontalGroup(
            ind_data1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_data1Layout.setVerticalGroup(
            ind_data1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btnThongKe.add(ind_data1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel15.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(204, 204, 204));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Thống kê");
        btnThongKe.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 30));

        btnBanHang.setBackground(new java.awt.Color(0, 0, 0));
        btnBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBanHangMousePressed(evt);
            }
        });
        btnBanHang.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ind_typo1.setOpaque(false);
        ind_typo1.setPreferredSize(new java.awt.Dimension(4, 40));

        javax.swing.GroupLayout ind_typo1Layout = new javax.swing.GroupLayout(ind_typo1);
        ind_typo1.setLayout(ind_typo1Layout);
        ind_typo1Layout.setHorizontalGroup(
            ind_typo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );
        ind_typo1Layout.setVerticalGroup(
            ind_typo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        btnBanHang.add(ind_typo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 40));

        jLabel18.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(204, 204, 204));
        jLabel18.setText("Bán hàng");
        btnBanHang.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        lblTenNhanVien.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        lblTenNhanVien.setForeground(new java.awt.Color(204, 204, 204));
        lblTenNhanVien.setText("Xin chào :");

        jLabel17.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(204, 204, 204));
        jLabel17.setText("Đổi mật khẩu");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel20.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 204, 204));
        jLabel20.setText("Đăng xuất");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sidepaneLayout = new javax.swing.GroupLayout(sidepane);
        sidepane.setLayout(sidepaneLayout);
        sidepaneLayout.setHorizontalGroup(
            sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidepaneLayout.createSequentialGroup()
                .addGroup(sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sidepaneLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblTenNhanVien))
                    .addGroup(sidepaneLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addComponent(jLabel17))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(btnBanHang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnQLSP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnQLNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnQLKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnQLDKM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidepaneLayout.setVerticalGroup(
            sidepaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidepaneLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTenNhanVien)
                .addGap(70, 70, 70)
                .addComponent(btnBanHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQLSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQLNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQLKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnQLDKM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel17)
                .addGap(41, 41, 41)
                .addComponent(jLabel20)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        pnlParent.add(sidepane, java.awt.BorderLayout.LINE_START);

        pnlRight.setBackground(new java.awt.Color(255, 255, 255));
        pnlRight.setMaximumSize(new java.awt.Dimension(1140, 799));
        pnlRight.setPreferredSize(new java.awt.Dimension(1140, 799));
        pnlRight.setLayout(new java.awt.CardLayout());

        pnlQLSP.setBackground(new java.awt.Color(255, 204, 204));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/icon/banner.png"))); // NOI18N

        javax.swing.GroupLayout pnlQLSPLayout = new javax.swing.GroupLayout(pnlQLSP);
        pnlQLSP.setLayout(pnlQLSPLayout);
        pnlQLSPLayout.setHorizontalGroup(
            pnlQLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlQLSPLayout.setVerticalGroup(
            pnlQLSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlRight.add(pnlQLSP, "card1");

        pnlQLNV.setBackground(new java.awt.Color(102, 255, 51));

        jLabel3.setText("Quản lý nhân viên");

        javax.swing.GroupLayout pnlQLNVLayout = new javax.swing.GroupLayout(pnlQLNV);
        pnlQLNV.setLayout(pnlQLNVLayout);
        pnlQLNVLayout.setHorizontalGroup(
            pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQLNVLayout.createSequentialGroup()
                .addGap(342, 342, 342)
                .addComponent(jLabel3)
                .addContainerGap(708, Short.MAX_VALUE))
        );
        pnlQLNVLayout.setVerticalGroup(
            pnlQLNVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQLNVLayout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(jLabel3)
                .addContainerGap(496, Short.MAX_VALUE))
        );

        pnlRight.add(pnlQLNV, "card2");

        pnlQLKH.setBackground(new java.awt.Color(255, 102, 51));

        javax.swing.GroupLayout pnlQLKHLayout = new javax.swing.GroupLayout(pnlQLKH);
        pnlQLKH.setLayout(pnlQLKHLayout);
        pnlQLKHLayout.setHorizontalGroup(
            pnlQLKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1153, Short.MAX_VALUE)
        );
        pnlQLKHLayout.setVerticalGroup(
            pnlQLKHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );

        pnlRight.add(pnlQLKH, "card1");

        pnlQLVC.setBackground(new java.awt.Color(255, 153, 153));

        jLabel11.setText("Quản lý Voucher");

        javax.swing.GroupLayout pnlQLVCLayout = new javax.swing.GroupLayout(pnlQLVC);
        pnlQLVC.setLayout(pnlQLVCLayout);
        pnlQLVCLayout.setHorizontalGroup(
            pnlQLVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQLVCLayout.createSequentialGroup()
                .addGap(388, 388, 388)
                .addComponent(jLabel11)
                .addContainerGap(669, Short.MAX_VALUE))
        );
        pnlQLVCLayout.setVerticalGroup(
            pnlQLVCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQLVCLayout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jLabel11)
                .addContainerGap(489, Short.MAX_VALUE))
        );

        pnlRight.add(pnlQLVC, "card1");

        pnlQLDKM.setBackground(new java.awt.Color(102, 255, 255));

        jLabel4.setText("Quản lý đợt khuyến mại");

        javax.swing.GroupLayout pnlQLDKMLayout = new javax.swing.GroupLayout(pnlQLDKM);
        pnlQLDKM.setLayout(pnlQLDKMLayout);
        pnlQLDKMLayout.setHorizontalGroup(
            pnlQLDKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlQLDKMLayout.createSequentialGroup()
                .addContainerGap(603, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(413, 413, 413))
        );
        pnlQLDKMLayout.setVerticalGroup(
            pnlQLDKMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlQLDKMLayout.createSequentialGroup()
                .addGap(308, 308, 308)
                .addComponent(jLabel4)
                .addContainerGap(473, Short.MAX_VALUE))
        );

        pnlRight.add(pnlQLDKM, "card1");

        pnlParent.add(pnlRight, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlParent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    int xy, xx;
    private void sidepaneMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidepaneMouseDragged
        // TODO add your handling code here:

    }//GEN-LAST:event_sidepaneMouseDragged

    private void sidepaneMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sidepaneMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_sidepaneMousePressed

    private void btnQLSPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLSPMousePressed
        // TODO add your handling code here:
        pnlRight.removeAll();
        pnlRight.add(new viewQLSanPham());
        setColor(btnQLSP);
        resetColor(btnQLDKM);
        resetColor(btnQLNV);
        resetColor(btnQLKH);
        resetColor(btnThongKe);
        resetColor(btnBanHang);

        ind_typo.setOpaque(true);
        ind_typo1.setOpaque(false);
        ind_data.setOpaque(false);
        ind_fonts.setOpaque(false);
        ind_icons.setOpaque(false);
        ind_data1.setOpaque(false);


    }//GEN-LAST:event_btnQLSPMousePressed

    private void btnQLNVMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLNVMousePressed
        // TODO add your handling code here:
        pnlRight.removeAll();
        pnlRight.add(new viewQLNhanVien());
        setColor(btnQLNV);
        resetColor(btnQLDKM);
        resetColor(btnQLSP);
        resetColor(btnQLKH);
        resetColor(btnThongKe);
        resetColor(btnBanHang);

        //indicators
        ind_typo.setOpaque(false);
        ind_typo1.setOpaque(false);
        ind_data.setOpaque(false);
        ind_fonts.setOpaque(true);
        ind_icons.setOpaque(false);
        ind_data1.setOpaque(false);


    }//GEN-LAST:event_btnQLNVMousePressed

    private void btnQLKHMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLKHMousePressed
        // TODO add your handling code here:
        
        pnlRight.removeAll();
        pnlRight.add(new QuanLyKhachHang());
        setColor(btnQLKH);
        resetColor(btnQLDKM);
        resetColor(btnQLNV);
        resetColor(btnQLSP);
        resetColor(btnThongKe);
        resetColor(btnBanHang);

        ind_typo.setOpaque(true);
        ind_typo1.setOpaque(false);
        ind_data.setOpaque(false);
        ind_fonts.setOpaque(false);
        ind_icons.setOpaque(false);
        ind_data1.setOpaque(false);
       

    }//GEN-LAST:event_btnQLKHMousePressed

    private void btnQLDKMMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnQLDKMMousePressed
        // TODO add your handling code here:
        this.pnlRight.removeAll();
        this.pnlRight.add(new viewQLKhuyenMai());
        setColor(btnQLDKM);
        resetColor(btnQLSP);
        resetColor(btnQLNV);
        resetColor(btnQLKH);
        resetColor(btnThongKe);
        resetColor(btnBanHang);

        ind_typo.setOpaque(false);
        ind_typo1.setOpaque(false);
        ind_data.setOpaque(true);
        ind_fonts.setOpaque(false);
        ind_icons.setOpaque(false);
        ind_data1.setOpaque(false);

        cardLayout.last(pnlRight);
    }//GEN-LAST:event_btnQLDKMMousePressed


    private void lblMaximizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMaximizeMousePressed
        if (TrangChu.this.getExtendedState() == MAXIMIZED_BOTH) {
            TrangChu.this.setExtendedState(JFrame.NORMAL);
        } else {
            TrangChu.this.setExtendedState(MAXIMIZED_BOTH);
        }
    }//GEN-LAST:event_lblMaximizeMousePressed

    private void lblCloseMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCloseMousePressed
        System.exit(0);
    }//GEN-LAST:event_lblCloseMousePressed

    private void lblMinimizeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMinimizeMousePressed
        TrangChu.this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_lblMinimizeMousePressed

    private void btnThongKeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMousePressed
        // TODO add your handling code here:
        pnlRight.removeAll();
        pnlRight.add(new viewThongKe());
        setColor(btnThongKe);
        resetColor(btnQLDKM);
        resetColor(btnQLSP);
        resetColor(btnQLKH);
        resetColor(btnQLNV);
        resetColor(btnBanHang);

        //indicators
        ind_typo.setOpaque(false);
        ind_typo1.setOpaque(false);
        ind_data1.setOpaque(true);
        ind_data.setOpaque(false);
        ind_fonts.setOpaque(false);
        ind_icons.setOpaque(false);
    }//GEN-LAST:event_btnThongKeMousePressed

    private void btnBanHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBanHangMousePressed
        // TODO add your handling code here:
        pnlRight.removeAll();
        pnlRight.add(new viewBanHang(nhanVien));
        setColor(btnBanHang);
        resetColor(btnThongKe);
        resetColor(btnQLDKM);
        resetColor(btnQLSP);
        resetColor(btnQLKH);
        resetColor(btnQLNV);

        //indicators
        ind_typo.setOpaque(false);
        ind_typo1.setOpaque(true);
        ind_data1.setOpaque(false);
        ind_data.setOpaque(false);
        ind_fonts.setOpaque(false);
        ind_icons.setOpaque(false);
    }//GEN-LAST:event_btnBanHangMousePressed

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất không?", "Đăng xuất", JOptionPane.YES_NO_OPTION);
        if(choice != JOptionPane.YES_OPTION){
            return;
        }
        new viewLogin().setVisible(true);
        this.setVisible(false);
        JOptionPane.showMessageDialog(this, "Đăng xuất thành công");
    }//GEN-LAST:event_jLabel20MouseClicked

    // set and reset color
    void setColor(JPanel panel) {
        panel.setBackground(Color.GRAY);
    }

    void resetColor(JPanel panel) {
        panel.setBackground(Color.BLACK);
    }

    void show(Component com) {
        pnlRight.removeAll();
        pnlRight.add(com);
        pnlRight.repaint();
        pnlRight.revalidate();
    }

    /**
     * @param args the command line arguments
     */
    public static TrangChu tc = new TrangChu(nhanVien);

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrangChu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                tc.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnBanHang;
    private javax.swing.JPanel btnQLDKM;
    private javax.swing.JPanel btnQLKH;
    private javax.swing.JPanel btnQLNV;
    private javax.swing.JPanel btnQLSP;
    private javax.swing.JPanel btnThongKe;
    private javax.swing.JPanel ind_data;
    private javax.swing.JPanel ind_data1;
    private javax.swing.JPanel ind_fonts;
    private javax.swing.JPanel ind_icons;
    private javax.swing.JPanel ind_typo;
    private javax.swing.JPanel ind_typo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblClose;
    private javax.swing.JLabel lblMaximize;
    private javax.swing.JLabel lblMinimize;
    private javax.swing.JLabel lblTenNhanVien;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlActions;
    private javax.swing.JPanel pnlParent;
    private javax.swing.JPanel pnlQLDKM;
    private javax.swing.JPanel pnlQLKH;
    private javax.swing.JPanel pnlQLNV;
    private javax.swing.JPanel pnlQLSP;
    private javax.swing.JPanel pnlQLVC;
    public javax.swing.JPanel pnlRight;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JPanel pnlTop;
    private javax.swing.JPanel sidepane;
    // End of variables declaration//GEN-END:variables
}
