/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import application.Main;
import domainModel.HoaDon;
import domainModel.HoaDonChiTiet;
import java.awt.Desktop;
import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import repositories.HoaDonRepository;
import service.ServiceHoaDon;
import service.ServiceHoaDonChiTiet;
import service.impl.ServiceHoaDonChiTietImpl;
import service.impl.ServiceHoaDonImpl;
import swing.ThongBao;
import view.viewBanHang;

/**
 *
 * @author dongl
 */
public class viewHoaDonCho extends javax.swing.JFrame {

    /**
     * Creates new form viewHoaDonCho
     */
    ServiceHoaDon ss = new ServiceHoaDonImpl();
    ServiceHoaDonChiTiet ssHDCT = new ServiceHoaDonChiTietImpl();
    public HoaDon hd = new HoaDon();
    Integer stt = 1;
    TrangChu trangChu = new TrangChu(null);
    DecimalFormat df = new DecimalFormat("#,###");

    public viewHoaDonCho() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.loadTable();
    }
    
    public void loadHoaDon(HoaDon hd) {
        viewBanHang x = new viewBanHang(null);
        int soThuTu = 1;
        SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
        x.lblMaHD.setText(hd.getMa());
        x.lblTongTien.setText(hd.getTongTien() + "");
        x.txtSDT.setText(hd.getKhachHang() == null ? "" : hd.getKhachHang().getSdt());
        x.txtTenKH.setText(hd.getKhachHang() == null ? "" : hd.getKhachHang().getHoTen());
        x.txtNgayTao.setText(format.format(hd.getNgayTao()));
        //x.txtNgayThanhToan.setText(format.format(hd.getNgayThanhToan()));
        x.lblNhanVien.setText(hd.getNhanVien().getHoTen());
        
        x.dtm = (DefaultTableModel) x.tblHoaDon.getModel();
        x.dtm.setRowCount(0);
        for (HoaDonChiTiet hdct : ssHDCT.getListByMaHD(hd.getMa())) {
            x.dtm.addRow(new Object[]{
                soThuTu++, hdct.getIdChiTietSanPham().getMa(), hdct.getIdChiTietSanPham().getBia().getTen(), hdct.getIdChiTietSanPham().getLoaiSP().getTen(),
                hdct.getIdChiTietSanPham().getTheTich(), hdct.getIdChiTietSanPham().getNongDoCon(), hdct.getIdChiTietSanPham().getTrangThai() == 0 ? "Lon" : "Thùng",
                hdct.getSoLuong(), df.format(hdct.getDonGia())
            });
        }
        x.loadTongTien();
        TrangChu.tc.pnlRight.removeAll();
        TrangChu.tc.pnlRight.add(x);
    }

    private void loadTable() {
        DefaultTableModel dtm = (DefaultTableModel) this.tblHoaDon.getModel();
        dtm.setRowCount(0);
        SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
        
        for (HoaDon hoaDon : ss.getListHDChuaTT()) {
            Integer soLuong = 0;
            for (HoaDonChiTiet x : ssHDCT.getListByMaHD(hoaDon.getMa())) {
                soLuong += x.getSoLuong();
            }
            dtm.addRow(new Object[]{
                stt++, hoaDon.getMa(), format.format(hoaDon.getNgayTao()), soLuong, hoaDon.getKhachHang()==null?" ": hoaDon.getKhachHang().getHoTen()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        btnXacNhan = new swing.ButtonCustom();
        jLabel1 = new javax.swing.JLabel();
        btnHuyHoaDon = new swing.ButtonCustom();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        tblHoaDon.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã HĐ", "Ngày Tạo", "Số lượng", "Khách hàng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDon.setRowHeight(40);
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        btnXacNhan.setBackground(new java.awt.Color(255, 0, 0));
        btnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnXacNhan.setText("Xác nhận");
        btnXacNhan.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Danh sách hóa đơn chưa thanh toán");

        btnHuyHoaDon.setBackground(new java.awt.Color(255, 0, 0));
        btnHuyHoaDon.setForeground(new java.awt.Color(255, 255, 255));
        btnHuyHoaDon.setText("Hủy Hóa Đơn");
        btnHuyHoaDon.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        btnHuyHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyHoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 799, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHuyHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHuyHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:

        int row = this.tblHoaDon.getSelectedRow();
        if (row == -1) {
            ThongBao tb = new ThongBao(this, ThongBao.Type.WARNING, ThongBao.Location.TOP_CENTER, "Bạn chưa chọn hóa đơn");
            tb.showNotification();
            return;
        }
        String maHD = this.tblHoaDon.getValueAt(row, 1).toString();
        HoaDon hoaDon = ss.getHoaDonByMa(maHD);
        this.loadHoaDon(hoaDon);
        
        this.setVisible(false);

//        SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy");
//        x.lblMaHD.setText(hd.getMa());
//        x.lblTongTien.setText(hd.getTongTien()+"");
//        x.txtTenKH.setText(hd.getKhachHang().getHoTen());
//        x.txtSDT.setText(hd.getKhachHang().getSdt());
//        x.txtNgayTao.setText(format.format(hd.getNgayTao()));
//        x.txtNgayThanhToan.setText(format.format(hd.getNgayThanhToan()));
//        x.lblNhanVien.setText(hd.getNhanVien().getHoTen());
//        
//        trangChu.pnlRight.removeAll();
//        trangChu.pnlRight.add(x);
//        trangChu.setVisible(true);
//        this.setVisible(false);
//        TrangChu.tc.setVisible(false);
        //System.exit(0);
    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:
//        viewBanHang x = new viewBanHang();
//        int row = this.tblHoaDon.getSelectedRow();
//        if(row == -1){
//            return;
//        }
//        String maHD = this.tblHoaDon.getValueAt(row, 1).toString();
//        HoaDon hd = ss.getHoaDonByMa(maHD);
//        x.loadHoaDon(hd);
//        this.setVisible(false);
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void btnHuyHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyHoaDonActionPerformed
        // TODO add your handling code here:
        int row = this.tblHoaDon.getSelectedRow();
        if (row == -1) {
            ThongBao tb = new ThongBao(this, ThongBao.Type.WARNING, ThongBao.Location.TOP_CENTER, "Bạn chưa chọn hóa đơn muốn hủy");
            tb.showNotification();
            return;
        }
        String maHD = this.tblHoaDon.getValueAt(row, 1).toString();
        HoaDon hoaDon = ss.getHoaDonByMa(maHD);
        System.out.println(hoaDon.getId());
        hoaDon.setTinhTrang(2);
        if(ss.update(hoaDon)){
            JOptionPane.showMessageDialog(this, "Hủy hóa đơn thành công");
                    this.loadTable();
        }else {
            JOptionPane.showMessageDialog(this, "Hủy hóa đơn thất bại");
        }
    }//GEN-LAST:event_btnHuyHoaDonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewHoaDonCho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewHoaDonCho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewHoaDonCho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewHoaDonCho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewHoaDonCho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ButtonCustom btnHuyHoaDon;
    private swing.ButtonCustom btnXacNhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHoaDon;
    // End of variables declaration//GEN-END:variables
}
